### PR TITLE
Add regex filter for messages

### PR DESCRIPTION
**Pull request by Nksama**
Regex filter for Message

### CODE REVIEW

**Comment by anonyindian** [comment]
@Nksama everything except that panic issue looks fine to me, we will be able to merge your PR once the issue is fixed!

**Comment by Nksama** [comment]
@anonyindian Fixrd

**Comment by anonyindian** [comment]
@Nksama it isn't fixed!

**Comment by Nksama** [comment]
@anonyindian now there is no bug , i guess

**Pull request merged**
